JornadaRails/config/routes.rb
Rails.application.routes.draw do

   root 'accounts#new'

   resources :accounts do
      resources :reviews
    end

end

JornadaRails/app/models/account.rb
class Account < ActiveRecord::Base
	has_many :reviews
	validates :title, presence: true, length: { minimum: 5 } 
end

JornadaRails/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :account
  validates :rate, :inclusion => { :in => 1..5, :message => 'Avalie o livro com uma nota entre 1 e 5'}
end

JornadaRails/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def create
		@account = Account.new(account_params)

		@account.save
		redirect_to @account
	end

	def new
		@account = Account.new
	end
		
	def show
		@account = Account.find(params[:id])
	end

	def index
		@accounts = Account.all
	end

	def edit
		@account = Account.find(params[:id])
	end

	def update
		@account = Account.find(params[:id])
		if @account.update(account_params)
			redirect_to @account
		else
			render 'edit'
		end
	end

	def destroy
		@account = Account.find(params[:id])
		@account.destroy

		redirect_to accounts_path
	end

	private
	def account_params
		params.require(:account).permit(:title, :author)
	end
end

JornadaRails/app/controllers/contas_controller.rb
class ContasController < ApplicationController
  def new
  end
end

JornadaRails/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
		@account = Account.find(params[:account_id])
		@review = @account.reviews.create(review_params)

		@review.save
		redirect_to account_path(@account)
	end

	private
	def review_params
		params.require(:review).permit(:rate, :comment)		
	end
end

JornadaRails/app/helpers/contas_helper.rb
module ContasHelper
end

JornadaRails/app/helpers/reviews_helper.rb
module ReviewsHelper
end

JornadaRails/app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
	<%if @account.errors.any? %>
		<div id="error">
			<h2>
				<%= pluralize(@account.errors.count, 'error') %> prohibited this book from begin saved:
			</h2>
			<ul>
				<% account.errors.full.messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<p> 
	<%= f.label :title %><br> 
	<%= f.text_field :title %> 
</p> 
<p> 
	<%= f.label :author %><br> 
	<%= f.text_field :author %> 
</p> 
<p> 
	<%= f.submit %> 
</p>
<% end %>

JornadaRails/app/views/accounts/index.html.erb
<h1>Listando contas</h1>

<table>
	<tr>
		<th>Title</th>
		<th>Autor</th>
	</tr>

	<% @accounts.each do |account| %>
		<tr>
			<td><%= account.title %></td>
			<td><%= account.author %></td>
			<td><%= link_to 'Destroy', account_path(account),
					method: :delete,
					data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Cadastrar conta', new_account_path %>

JornadaRails/app/views/accounts/new.html.erb
	
	<%= render 'form' %>

	<%= link_to 'Listar contas', accounts_path %>

JornadaRails/app/views/accounts/review.html.erb
<p>
	<strong>Title</strong>
	<%= @account.title %>
</p>

<p>
	<strong>Autor:</strong>
	<%= @account.author %>
</p>

<h2>Reviews</h2>
<% @account.reviews.each do |r| %>
	<p>
		<strong>Nota:</strong>
		<%= r.rate %>
	</p>

	<p>
		<strong>Comentário:</strong>
		<%= r.comment %>
	</p>
<%= end %>

<h2>Avalie esse livro:</h2>
<%= form_for([@account.reviews.build]) do |f| %>
	<p>
		<%= f.label :rate %><br>
		<%= f.range_field(:rate, in:1..5) %>
	</p>
	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

JornadaRails/app/views/accounts/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @account.title %>
</p>

<p>
	<strong>Autor:</strong>
	<%= @account.author %>
</p>

<%= link_to 'Listar contas', accounts_path %>
<%= link_to 'Editar', edit_account_path(@account) %>

JornadaRails/app/views/contas/new.html.erb
<%= render 'form' %>

<%= link_to 'Listar contas', accounts_path %>

JornadaRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JornadaRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>