ProjetoRubyOnRails/ContaBancaria/config/routes.rb
Rails.application.routes.draw do
  get 'accounts/index'

  root 'accounts#index'

  resources :accounts
  resources :users

end

ProjetoRubyOnRails/ContaBancaria/app/models/account.rb
class Account < ActiveRecord::Base
	validates :agency, presence: true, length: { maximum: 5 }
	validates :account_number, presence: true, length: { maximum: 6 }
	belongs_to :user
end

ProjetoRubyOnRails/ContaBancaria/app/models/user.rb
class User < ActiveRecord::Base
	has_one :account
	validates :name, presence: true, length: {maximum: 100}
	validates :cpf, presence: true, length: {maximum: 10}
end

ProjetoRubyOnRails/ContaBancaria/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def create
		@account = Account.new(account_params)

		@account.save
		redirect_to @account
	end

	def new
		@account = Account.new
	end

	def show	
		@account = Account.find(params[:id])
	end

	def authentication
		@account = Account.find_by(agency: params[:account][:agency])
             #   if @user && user.authenticate(params[:account][:account_number])
             #             
   			#	end 
	end

	def index
		@account = Account.new
	end

	def options
		@account = Account.find(params[:id])
	end

	def edit
		@account = Account.find(params[:id])
	end

	def update
		@account = Account.find(params[:id])
		if @account.update(account_params)
			redirect_to @account
		else
			render 'edit'
		end
	end

	def destroy
		@account = Account.find(params[:id])
		@account.destroy

		redirect_to accounts_path
	end

	private
	def account_params
		params.require(:account).permit(:agency, :account_number)
	end
end

ProjetoRubyOnRails/ContaBancaria/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ProjetoRubyOnRails/ContaBancaria/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
		if @user.save
			redirect_to @user, notice: "Titular cadastrado com sucesso!"
		else
			render action: :new
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :cpf, :agency, :account_number)	
	end
end

ProjetoRubyOnRails/ContaBancaria/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ProjetoRubyOnRails/ContaBancaria/app/helpers/accounts_helper.rb
module AccountsHelper
end

ProjetoRubyOnRails/ContaBancaria/app/helpers/application_helper.rb
module ApplicationHelper
end

ProjetoRubyOnRails/ContaBancaria/app/helpers/users_helper.rb
module UsersHelper
end

ProjetoRubyOnRails/ContaBancaria/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ProjetoRubyOnRails/ContaBancaria/app/views/accounts/_form_access.html.erb
<%= form_for @account do |f| %>
	<%if @account.errors.any? %>
		<div id="error">
			<h2>
				<%= pluralize(@account.errors.count, 'error') %> prohibited this account from begin saved:
			</h2>
			<ul>
				<% account.errors.full.messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<p> 
	<%= f.label :agency %><br> 
	<%= f.text_field :agency %> 
</p> 
<p> 
	<%= f.label :account_number %><br> 
	<%= f.text_field :account_number %> 
</p> 
<p> 
	<%= f.submit %> 
</p>
<% end %>

ProjetoRubyOnRails/ContaBancaria/app/views/accounts/index.html.erb
<h1>Listando contas</h1>

<table>
	<tr>
		<th>Agência</th>
		<th>Conta</th>
	</tr>

	<% @accounts.each do |account| %>
		<tr>
			<td><%= account.agency %></td>
			<td><%= account.accoun_number %></td>
			<td><%= link_to 'Destroy', account_path(account),
					method: :delete,
					data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Cadastrar conta', new_account_path %>

ProjetoRubyOnRails/ContaBancaria/app/views/accounts/show.html.erb
<h1>Olá <%= @user.user_name %></h1>
<%= link_to 'Sair', accounts_path %>
<p>
	<strong>Agência:</strong>
	<%= @account.agency %>
</p>

<p>
	<strong>Conta:</strong>
	<%= @account.account_number %>
</p>

<%= link_to 'Editar dados', accounts_path %>

<p>
	<strong>Saldo:</strong>
	<%= @account.balance %>
</p>

<h3>Operações</h3>
<%= link_to 'Saque', accounts_path %>
<%= link_to 'Depósito', accounts_path %>
<%= link_to 'Transferência', accounts_path %>

ProjetoRubyOnRails/ContaBancaria/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContaBancaria</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ProjetoRubyOnRails/ContaBancaria/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%if @user.errors.any? %>
		<div id="error">
			<h2>
				<%= pluralize(@user.errors.count, 'error') %> prohibited this user from begin saved:
			</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<p> 
	<%= f.label :name %><br> 
	<%= f.text_field :name %> 
</p> 
<p> 
	<%= f.label :cpf %><br> 
	<%= f.text_field :cpf %> 
</p>

<p> 
	<%= f.submit %> 
</p>
<% end %>

ProjetoRubyOnRails/ContaBancaria/app/views/users/edit.html.erb
<h1>Editing book<h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

ProjetoRubyOnRails/ContaBancaria/app/views/users/new.html.erb
	
	<%= link_to 'NOVO TITULAR', users_path %>
	<%= render 'form' %>

ProjetoRubyOnRails/ContaBancaria/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>